// src/app/lib/fetchPartsData.ts

// Example of static data for the form
export async function fetchPartsData() {
    return {
      years: ['2023', '2022', '2021'],
      makes: ['Toyota', 'Ford', 'BMW'],
      models: ['Camry', 'Mustang', 'X5'],
      parts: [
        "Front End Assembly",
        "Header Panel Assembly",
        "Spoiler/Valance, Front",
        "Grille",
        "Bumper Assembly, Front",
        "Bumper Guard, Front",
        "Bumper Reinforcement, Front",
        "Bumper Shock",
        "Radiator Core Support",
        "Fender",
        "Fender Extension",
        "Inner Fender",
        "Fender Molding",
        "Headlamp Assembly",
        "Front Lamp",
        "Hood",
        "Hood Hinge",
        "Cowl",
        "Door Assembly, Front",
        "Hood Strut",
        "Running Board",
        "Cowl Vent Panel",
        "Door Hinge, Front",
        "Door Window Regulator, Front",
        "Door Vent Window Regulator, Front",
        "Door Molding, Front",
        "Side View Mirror",
        "Door Handle",
        "Door Assembly, Rear or Back",
        "Door Hinge, Rear",
        "Door Window Regulator, Rear",
        "Door Molding, Rear",
        "A-Pillar",
        "Bumper End Cap",
        "Liner",
        "Pickup Topper",
        "Luggage Rack",
        "Roll Bar",
        "Rear Clip",
        "Rear Top Section",
        "Roof Assembly",
        "Sunroof Panel",
        "Pickup Truck Cab (Shell)",
        "Pickup Box Rear",
        "Pickup Box Front Panel",
        "Pickup Box Floor Pan",
        "Quarter Repair Panel",
        "Quarter Panel Assembly",
        "Quarter Extension",
        "Skirt",
        "Quarter Window Regulator, Rear",
        "Cab Clip",
        "Quarter Molding",
        "Tail Lamp",
        "Backup Lamp",
        "Side Marker Lamps, Rear",
        "Spoiler, Rear",
        "Decklid / Tailgate",
        "Trunk Lid Molding",
        "Hatchback Strut",
        "Valance, Rear",
        "Trunk Lid Hinge",
        "License Lamp",
        "High Mounted Stop Lamp",
        "Fuel Filler Door",
        "Fuel Cap",
        "Fuel Filler Neck",
        "Latches & Locks",
        "Tail Gate Hinge",
        "Tail Gate Window Regulator",
        "Tail Gate Molding",
        "Rear Window Washer Motor",
        "Rocker Panel Molding",
        "Bumper Assembly, Rear",
        "Bumper Reinforcement, Rear",
        "Bumper Filler Panel",
        "Bumper Guard, Rear",
        "Tail Panel",
        "Tail Finish Panel",
        "Floor Pan",
        "Fuel Tank",
        "Center Pillar",
        "Body Parts, Misc.",
        "Complete Interior",
        "Seat, Front",
        "Seat Track, Front",
        "Interior Trim Panel Front Door",
        "Interior Trim Panel Rear Door",
        "Headrest",
        "Seat Belt Assembly",
        "Motorized Seat Belt Track",
        "Seat, Rear",
        "Third Seat, (Station Wagon or Van)",
        "Parcel Shelf",
        "Carpet, Front",
        "Carpet, Rear",
        "Headliner",
        "Misc. Trim Pad",
        "Door Window Crank, Front",
        "Door Window Crank, Rear",
        "Boot Cover",
        "Accelerator Parts",
        "Steering Wheel",
        "Steering Shaft",
        "Steering Column",
        "Column Shift Lever",
        "Console",
        "Floor Shift Assembly",
        "Dash Assembly",
        "Dash Panel",
        "Dash Pad",
        "Air Bag",
        "Instrument Cluster Bezel",
        "Instrument Cluster",
        "Clock",
        "Speedometer Head /Cluster",
        "Tachometer",
        "Fuel Gauge",
        "Glove Box",
        "Clock Spring",
        "Interior Mirror",
        "Interior Sun Visor",
        "Windshield Frame",
        "Windshield Glass",
        "Back Glass",
        "Door Glass, Front",
        "Door Glass, Rear",
        "Door Vent Glass, Rear",
        "Door Vent Glass, Front",
        "Quarter Glass",
        "Roof Glass",
        "Special Glass",
        "Interior Parts, Misc.",
        "Engine Assembly",
        "Cylinder Block",
        "Crankshaft",
        "Piston",
        "Camshaft",
        "Cylinder Head",
        "Rocker Arm",
        "Timing Cover",
        "Harmonic Balancer",
        "Timing Belt Tension",
        "Oil Pan",
        "Oil Pump",
        "Connecting Rod",
        "Short Cylinder Block",
        "Timing Chain, Belt",
        "Timing Gears",
        "Intercooler",
        "Engine Oil Cooler",
        "Air Cleaner",
        "Carburetor",
        "Turbocharger/Supercharger",
        "Fuel Injection Parts",
        "Fuel Pump Assembly",
        "Water Pump",
        "Fan Blade",
        "Fan Clutch",
        "Exhaust Manifold",
        "Exhaust Assembly",
        "Intake Manifold",
        "Exhaust Cross Pipe",
        "Exhaust Pipe",
        "Tail Pipe",
        "Muffler",
        "Exhaust Resonator",
        "Catalytic Converter",
        "Air Flow Meter",
        "Throttle Body/Valve Assembly",
        "Air Injection Pump",
        "Brackets, Misc.",
        "Engine Mounts",
        "Camshaft Housing",
        "Valve Cover",
        "Vacuum Pump",
        "Filter/Water Separator",
        "Fuel Vapor Canister",
        "Engine Parts, Misc.",
        "Transmission/Transaxle Assembly",
        "Overdrive Unit",
        "Transaxle Housing",
        "Manual Transmission Parts",
        "Automatic Transmission Parts",
        "Pressure Plate",
        "Torque Converter",
        "Bell Housing",
        "Flywheel/Flex Plate",
        "Clutch Disc",
        "Transfer Case Adapter",
        "Transfer Case Assembly",
        "Front Transmission Pump",
        "Automatic Transmission Oil",
        "Automatic Transmission Pan",
        "Clutch Master Cylinder",
        "Clutch Slave Cylinder",
        "Transfer Case Motor",
        "Transmission Crossmember",
        "Drive Shaft, Front",
        "Drive Shaft, Rear",
        "Universal Slip Yoke",
        "Axle Assembly, Front",
        "Axle Assembly, Rear",
        "Axle Housing",
        "Axle Flange",
        "Carrier Case",
        "Carrier Assembly",
        "Differential Parts, Misc.",
        "Differential Flange",
        "Differential Case",
        "Differential Assembly",
        "Ring Gear and Pinion",
        "Axle Shaft",
        "Differential Side Gears",
        "Rear Independent Suspension Assembly",
        "Beam Axle, Loaded",
        "Suspension Crossmember/K-Frame",
        "Stub Axle, Rear",
        "Axle Parts, Misc.",
        "Frame",
        "Frame, Front",
        "Frame Rails, Upper & Lower",
        "Frame Horn",
        "Spring Hanger",
        "Upper Control Arm, Rear",
        "formerly Suspension Locating Arm",
        "formerly Suspension Trailing Arm",
        "Retainer",
        "Knuckle Support",
        "Knee",
        "Upper Control Arm, Front",
        "Lower Control Arm, Front",
        "Lower Control Arm, Rear",
        "Radius Arm, Front",
        "Spindle/Knuckle, Front",
        "Leaf Spring, Front",
        "Coil Spring",
        "Leaf Spring, Rear",
        "Air Spring",
        "Front Axle I-Beam (  WD)",
        "Torsion Bar",
        "Suspension Compressor/Pump",
        "Suspension Trunion Arm",
        "Stabilizer Bar",
        "Shock Absorber",
        "Strut",
        "Brakes, Front",
        "Brakes, Rear",
        "Brake Parts, Misc. Front",
        "Brake Parts, Misc. Rear",
        "Caliper",
        "Locking Hubs",
        "Hub",
        "Brake Proportioning Valve",
        "Power Brake Booster",
        "Brake Master Cylinder",
        "Brake Shoes",
        "Backing Plate, Front",
        "Backing Plate, Rear",
        "Anti Lock Brake Parts",
        "Brake/Clutch Pedal Box",
        "Emergency Brake Parts",
        "Wheel Speed Sensor",
        "Power Steering Assembly",
        "Steering Gear/Rack & Pinion",
        "Tie Rod",
        "Power Steering Pump",
        "Power Steering Control Valve",
        "Power Steering Pressure Hose",
        "Power Steering Pressure Cylinder",
        "Pitman Arm",
        "Drive Link",
        "Idler Arm",
        "Wheel",
        "Wheel Bearing, Front",
        "Wheel Bearing, Rear",
        "Lug Wrench",
        "Jack",
        "Inner Fender Liner",
        "Spare Wheel Carrier",
        "Wheel Cover",
        "Trim Ring",
        "Hub Cap",
        "Tires",
        "Trailer Hitch",
        "Electronic Engine Control Modules",
        "Electronic Chassis Control Modules",
        "Electronic Parts, Misc.",
        "Info-GPS-TV Screen",
        "Steering or Suspension Parts, Misc.",
        "Battery",
        "Alternator",
        "Voltage Regulator",
        "Generator",
        "Starter Motor",
        "Starter Solenoid",
        "Distributor",
        "Battery Tray",
        "EGR Maintenance Reminder",
        "Fuel Pacer System",
        "Coil",
        "Seat Belt Motor",
        "Seat Motor",
        "Horn",
        "Electrical Relay",
        "Blower Motor",
        "Window Defogger, Rear",
        "Power Window Motor",
        "Wiper Motor, Rear",
        "Headlamp Motor",
        "Wiper Motor, Windshield",
        "Wiper Transmission",
        "Windshield Washer Reservoir",
        "Windshield Washer Motor",
        "Horn Ring",
        "Horn Button",
        "Windshield Washer Nozzle",
        "Power Door Motor",
        "Computer Module, Anti Lock Brake",
        "Power Door Module",
        "Power Seat Module",
        "Ignition Coil",
        "Horns",
        "Engine Control Module",
        "Transmission Control Module",
        "Ignition System",
        "Starter Switch",
        "Thermal Time Switch",
        "Knock Sensor",
        "Headlight Assembly"
    ]
    ,
    };
  }
  